### ISSUE TITLE
Contact Us template not posting to the controller method

### ISSUE THREAD

**Issue by AaronLeoCooper** [siyingloh/Durrows#1]
Hi @siyingloh!

I've had a look through your contact us template and I believe you're missing an `action` attribute on your `contactus` form on line 38:

https://github.com/siyingloh/Durrows/blob/147a61d037b675cf6136d4d4cdcde8baf8bc33b4/contactus.blade.php#L38

In order for a form to post to the backend, you'll need to give it:

- a `method="post"` attribute (already there)
- an `action="action location"` attribute (currently missing)
- a special `@csrf` Laravel token just inside the form (already there)

And since the form I can see already has a `<button>` inside it with `type="submit"`, clicking this should post all of the form data from all `input` and `textarea` fields that can be found inside the form. I think the only thing missing is the `action` attribute, which tells the form where to send the data to.

Laravel shares a bit of information relating to URL generation of controller actions here: https://laravel.com/docs/5.7/urls#urls-for-controller-actions.

Here's what I'd first suggest trying on line 38 to include an `action`:

<pre><code>&lt;form id="validate" enctype="application/x-www-form-urlencoded" role="form" class="profile_form" novalidate="novalidate" method="post" <strong>action="{{ action('frontend\ContactusController@save') }}"</strong>&gt;</code></pre>

Alternatively if this doesn't work for some reason, you can also try just using the direct URL path in the action as it appears inside your `web.php` routes, like this:

<pre><code>&lt;form id="validate" enctype="application/x-www-form-urlencoded" role="form" class="profile_form" novalidate="novalidate" method="post" <strong>action="/contactus"</strong>&gt;</code></pre>

Hope this helps, let me know if you run into any issues! 😄

**Comment by siyingloh** [comment]
Hi @AaronLeoCooper ,  
Thanks for pointing that out. However the error was not due to the missing action as contactus page was working fine without it. 
I have looked at the codes around that section as realised that `designerSignUp.balde.php` was missing.

I have thus updated and now the form was able to be redirected. I am now faced with a new issue where the temp_subject is throwing an error 
https://github.com/siyingloh/Durrows/blob/c1d3261dbfd8c7d703d1fa62081cff2b0a7dd232/designerSignupController.php#L34

I assume that the subject naming convention has been done wrongly on my side as referenced from the mail template, but is there a way where I can find where the correct naming convention is to point it to the correct object?

**Comment by AaronLeoCooper** [comment]
Hey @siyingloh! I see ok, is everything worked as expected now for you?

**Comment by siyingloh** [comment]
@AaronLeoCooper 
Yes, the previous error that I had mentioned on the chat has also been fixed too. The form is working well now :)
