### ISSUE TITLE
Joining tables on SQL to retrieve users.name and users.client_last_name 

### ISSUE THREAD

**Issue by siyingloh** [siyingloh/Durrows#2]
As I have currently tried to join tables for users and portfolio based users.id = portfolio.portfolio_user_id
I am having difficulty in understanding how to retrieve users.name and users.client_last_names which are values in users table into the display.
https://github.com/siyingloh/Durrows/blob/cc96af6a5c556c63c26387f12e583eaed265612d/designdisplay.blade.php#L83
Right now in display I have shown the user by it's ID as on [https://durrows.com/portfoliotest]( https://durrows.com/portfoliotest)
But I would like to be able to show the ID as it's user's name instead. 
I have tried using 
```
<a href="/profile/{{ $result->portfolio_user_id  }}">{{ $result->name }}</a>
<a href="/profile/{{ $result->portfolio_user_id  }}">{{ $result->users.name}}</a>
```
which has both returned an error, and I'm assuming that I might have joined it wrongly in the DesignDisplayController
https://github.com/siyingloh/Durrows/blob/cc96af6a5c556c63c26387f12e583eaed265612d/DesignDisplayController.php#L75-L82

Also another issue faced was the pinterest logo that does not show up
https://github.com/siyingloh/Durrows/blob/cc96af6a5c556c63c26387f12e583eaed265612d/designdisplay.blade.php#L82

**Comment by AaronLeoCooper** [comment]
Hey @siyingloh! Sorry for my late response, yesterday was just a bit of a crazy day for me haha.

**Displaying user name instead of ID**

The first thing I always do in these types of situations is to get a clear snapshot of what's currently being returned from the DB in the query. The quickest way I'm aware of in PHP is to use either `var_dump()` or `print_r()`. You might sometimes need to try both to see which gives you a clearer picture of the data structure you need to check on. Immediately after your DB query, try adding this:

```
print_r($result);
```

When the view loads, you should be able to see the data printed at the top of the HTML. If it's looking messy or hard to read due to CSS styling or whatnot, try adding an `exit();` on the line after the `print_r` function and it'll stop the rest of the view from loading. Once you can see the structure, you should hopefully be able to better understand how the data is structured and see whether or not the fields you need are present and where they are located.

As for your query, I'm afraid I don't have a PHP server on my machine at work so I'll need to give this a try later. For the time being though, can you share with me what your tables look like in the DB? It'll also be useful to see the model PHP files for `portfolio` and `portfolio_images` if possible? Then we can check if all of the required fields you need are being openly exposed from the model or if they've been made private.

**Pintrest logo not showing**

Just something quick to try, though it may not fix your problem, just make sure first that the HTML attributes on the `<a>` tag are correctly formatted. I see that `data-pin-round =true` should probably be: `data-pin-round="true"`

I haven't used the Pintrest widgets before in a website, but just looking at their help page now (https://help.pintrest.com/en/articles/website-widgets), these are the other possible values I see you can use for the `data-pin-do` attribute:

- `data-pin-do="embedBoard"`
- `data-pin-do="embedUser"`
- `data-pin-do="embedPin"`

I managed to find ``data-pin-do="buttonBookmark"`` as well under their widget builder, which is the one you used and your example looks correct (with the `<script>` tag as well I can see you've already added), other than that minor thing I mentioned above. If it's still not working, you could maybe try one of the other values and see if it works?

**Comment by siyingloh** [comment]
@AaronLeoCooper Hi Aaron, I have looked through the vardump code for $result and tried to merge users table into it as it currently does not read the values from that table which I need.
![image](https://user-images.githubusercontent.com/26007451/47001126-54850400-d15c-11e8-95af-e766112c6b11.png)

However I tried using 
```
->leftjoin('users', 'portfolio.portfolio_user_id', 'users.id')
->select('users.*')
```
within this 
https://github.com/siyingloh/Durrows/blob/cc96af6a5c556c63c26387f12e583eaed265612d/DesignDisplayController.php#L61-L68

And the display seems to be showing the same values fetched.

**Comment by AaronLeoCooper** [comment]
Hi @siyingloh, sorry for my delay getting back to you again, did read your message but have been struggling to find time lately. Did your change to add `->leftJoin('users', 'users.id', '=', 'portfolio.portfolio_user_id')` get the data structure you were hoping for?

If not, I'll look at this today and help you build up the query you need. Can you provide me with samples of your tables for portfolio, portfolio_images & user? Assuming those are the tables you need to create a join query for.
